import { MaterialPalette } from "../../../material-1.0/ui/styling/material_palette.slint";

export component ScrollBar {
    in property <bool> enabled;
    out property <bool> has_hover: touch_area.has_hover;
    in_out property <bool> horizontal;
    in_out property <length> maximum;
    in_out property <length> page_size;
    in_out property <length> value;
    in property <ScrollBarPolicy> policy: ScrollBarPolicy.as_needed;

    property <length> track_size: root.horizontal ? root.width - 2 * root.offset : root.height - 2 * root.offset;
    property <length> step_size: 10px;
    property <length> offset: 2px;
    property <length> track_gap: 8px;

    visible: (self.policy == ScrollBarPolicy.always_on) || (self.policy == ScrollBarPolicy.as_needed && self.maximum > 0);

    Rectangle {
        width: !root.horizontal ? 8px : max(0px, thumb.x - root.track_gap);
        height: root.horizontal ? 8px : max(0px, thumb.y - root.track_gap);
        x: !root.horizontal ? parent.width - self.width - 4px : 0;
        y: root.horizontal ? parent.height - self.height - 4px : 0;

        border_radius: 4px;
        background: MaterialPalette.secondary_container;
    }

    Rectangle {
        width: !root.horizontal ? 8px : max(0px, parent.width - (thumb.x + thumb.width + root.track_gap));
        height: root.horizontal ? 8px : max(0px, parent.height - (thumb.y + thumb.height + root.track_gap));
        x: !root.horizontal ? parent.width - self.width - 4px : thumb.x + thumb.width + root.track_gap;
        y: root.horizontal ? parent.height - self.height - 4px : thumb.y + thumb.height + root.track_gap;

        border_radius: 4px;
        background: MaterialPalette.secondary_container;
    }

	thumb := Rectangle {
			property <length> thumb_length: root.horizontal ? parent.height : root.maximum <= 0phx ? 0phx : max(min(32px, root.height), root.track-size * (root.page-size / (root.maximum + root.page-size)));

			property <length> normal_thickness: 8px;
    		width:  !root.horizontal ? self.normal_thickness : self.thumb_length;
    		height: root.horizontal ? self.normal_thickness : self.thumb_length;
    		x: !root.horizontal ? parent.width - self.width - 4px : root.offset + (root.track_size - self.width) * (-root.value / max(1px, root.maximum));
			y: root.horizontal ? parent.height - self.height - 4px : root.offset + (root.track_size - self.height) * (-root.value / max(1px, root.maximum));
			border-radius: (root.horizontal ? self.height : self.width) / 2;

    		background: MaterialPalette.primary;
    	}

    touch_area := TouchArea {
        property <length> pressed_value;
        width: parent.width;
        height: parent.height;

        pointer_event(event) => {
            if (event.button == PointerEventButton.left && event.kind == PointerEventKind.down) {
                self.pressed_value = -root.value;
            }
        }

        moved => {
            if (self.enabled && self.pressed) {
                root.value = -max(0px, min(root.maximum, self.pressed_value + (
                    root.horizontal ? (self.mouse_x - self.pressed_x) * (root.maximum / max(1px, root.track_size - thumb.width))
                                   : (self.mouse_y - self.pressed_y) * (root.maximum / max(1px, root.track_size - thumb.height))
                )));
            }
        }

        scroll_event(event) => {
            if (root.horizontal && event.delta_x != 0) {
                root.value = max(-root.maximum, min(0px, root.value + event.delta_x));
                return accept;
            } else if (!root.horizontal && event.delta_y != 0) {
                root.value = max(-root.maximum, min(0px, root.value + event.delta_y));
                return accept;
            }
            reject
        }

        changed has_hover => {
            if !self.has_hover && !hide_timer.running {
                hide_timer.running = true;
            }
        }

        changed pressed => {
            if self.pressed && hide_timer.running {
                hide_timer.running = false;
            }
        }
    }

    changed value => {
        if !touch_area.has_hover && !hide_timer.running {
            hide_timer.running = true;
        }
    }

    hide_timer := Timer {
        interval: 1.5s;
        running: false;
        triggered => {
            self.running = false;
        }
    }
}

export component ScrollView {
    in property <bool> enabled: true;
    out property <length> visible_width <=> flickable.width;
    out property <length> visible_height <=> flickable.height;
    in_out property <length> viewport_width <=> flickable.viewport_width;
    in_out property <length> viewport_height <=> flickable.viewport_height;
    in_out property <length> viewport_x <=> flickable.viewport_x;
    in_out property <length> viewport_y <=> flickable.viewport_y;
    in property <ScrollBarPolicy> vertical_scrollbar_policy <=> vertical_bar.policy;
    in property <ScrollBarPolicy> horizontal_scrollbar_policy <=> horizontal_bar.policy;
    in_out property <bool> has_focus;

    callback scrolled <=> flickable.flicked;

    property <length> scroll_bar_padding: 4px;
    property <length> interactive_bar_size: 32px;
    property <length> layout_bar_size: 8px;

    min_height: 50px;
    min_width: 50px;
    horizontal_stretch: 1;
    vertical_stretch: 1;
    preferred_height: 100%;
    preferred_width: 100%;

    flickable := Flickable {
        x: 0;
        y: 0;
        viewport_y <=> vertical_bar.value;
        viewport_x <=> horizontal_bar.value;

        width: root.width - (root.vertical_scrollbar_policy != ScrollBarPolicy.always_off ? root.layout_bar_size : 0);
        height: root.height - 0;

        @children
    }

    vertical_bar := ScrollBar {
        enabled: root.enabled;

        x: parent.width - self.width;
        y: 0;
        width: root.visible ? root.interactive_bar_size : 0;
        height: root.vertical_scrollbar_policy != ScrollBarPolicy.always_off ? parent.height - horizontal_bar.height : parent.height;

        horizontal: false;
        maximum: flickable.viewport_height - flickable.height;
        page_size: flickable.height;
    }

    horizontal_bar := ScrollBar {
        enabled: root.enabled;

        x: 0;
        y: parent.height - self.height;
        width: vertical_bar.visible ? parent.width - vertical_bar.width : parent.width;
        height: root.horizontal_scrollbar_policy != ScrollBarPolicy.always_off ? root.interactive_bar_size : 0;
        horizontal: true;
        maximum: flickable.viewport_width - flickable.width;
        page_size: flickable.width;
    }
}