import { TrackData } from "../../data/track_data.slint";

import {
    MaterialPalette,
    MaterialTypography,
    MaterialStyleMetrics,
    StateLayerArea,
    MaterialText
} from "../../../material-1.0/material.slint";

export component Track {
in property <TrackData> track;
    in property <bool> playing;

    callback clicked();

    if track.visible : Rectangle {
        background: root.playing ? MaterialPalette.secondary_container : MaterialPalette.surface;

        border-radius: MaterialStyleMetrics.border_radius_12;

        StateLayerArea {
            color: root.playing ? MaterialPalette.on_secondary_container : MaterialPalette.on_surface;
            border-radius: parent.border_radius;

            clicked => { root.clicked(); }

            HorizontalLayout {
                spacing: MaterialStyleMetrics.spacing_16;
                padding: MaterialStyleMetrics.padding_12;

                padding-left: root.playing ? MaterialStyleMetrics.padding_24 : MaterialStyleMetrics.padding_12;

                Rectangle {
                    width: MaterialStyleMetrics.size_64;
                    height: MaterialStyleMetrics.size_64;
                    border-radius: MaterialStyleMetrics.border_radius_8;
                    clip: true;

                    Image {
                        width: 100%;
                        height: 100%;
                        source: track.cover;
                        image-fit: cover;
                    }
                }

                VerticalLayout {
                    alignment: center;
                    horizontal-stretch: 1;

                    MaterialText {
                        text: track.title;
                        style: MaterialTypography.title_medium;
                        color: root.playing ? MaterialPalette.on_secondary_container : MaterialPalette.on_surface;
                        overflow: elide;
                    }

                    MaterialText {
                        text: track.artist;
                        style: MaterialTypography.body_medium;
                        color: root.playing ? MaterialPalette.on_secondary_container : MaterialPalette.on_surface_variant;
                        overflow: elide;
                    }
                }

                MaterialText {
                    text: track.time;
                    style: MaterialTypography.label_medium;
                    color: root.playing ? MaterialPalette.on_secondary_container : MaterialPalette.on_surface_variant;
                    vertical-alignment: center;
                }
            }
        }
    }
}